#304 Implement pagination
learnhubmk/app pull request #348
Opened 2024-06-13 16:05 UTC by aleksandarmicev

Implement pagination

2024-06-18 23:35 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
> +      const data = await fetchItems(currentPage, itemsPerPage);
try catch here

2024-06-18 23:37 UTC, edichoska commented on components/reusable-components/pagination/StructurePagination.tsx
> +  };
this should be in another PR. Also we should have pages, like 1,2,3,4,5 not next and previous

2024-06-18 23:39 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
> +  const options = [25, 50, 100];
the name should be all uppercase letter, it is a convention, also use more descriptive name

2024-06-18 23:46 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
> +  }, [itemsPerPage]);
consider the following scenario here:
we have 100 users, we are showing 25 per page, user is on page 4, and changes in the dropdown to 50 per page. So now we only have 2 pages, and not 4.
How can we handle that scenario?

2024-06-29 12:34 UTC, edichoska commented
@aleksandarmicev Can you fix this comments when you have the time, so we can merge this?
Also resolve the conflict with the project Section

2024-07-03 20:02 UTC, edichoska requested changes

2024-07-03 20:02 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
> +  const [ITEMS_PER_PAGE, SET_ITEMS_PER_PAGE] = useState(25);
naming const with capital letters doesnt apply to useState, please revert this changes

2024-07-03 20:02 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
> +  }, [itemsPerPage]);
@aleksandarmicev also please consider the scenario in the comment above. Please tag me when this is done

2024-07-14 11:54 UTC, edichoska commented
@aleksandarmicev resolve conflicts here

2024-07-14 22:04 UTC, aleksandarmicev commented
> @aleksandarmicev resolve conflicts here

Conflicts are just resolved, merged new changes from the staging

2024-07-14 22:06 UTC, edichoska commented on components/reusable-components/pagination/Dropdown.tsx
> +export default Dropdown;
Don't we already have a reusable dropdown component?

2024-07-18 11:37 UTC, edichoska commented
@aleksandarmicev Please use this in combination with the table and some dummy data to test if this is working, and attach a video. 🙏

2024-09-03 21:23 UTC, edichoska commented
@aleksandarmicev Is this tested? Could you maybe add it, in the reusable table implementation in content-panel > blogs?

2024-09-08 13:05 UTC, edichoska requested changes

2024-09-08 13:05 UTC, edichoska commented on components/reusable-components/pagination/HomePagination.tsx
Maybe a better approach here would be to create a context. Here you should also consider that we will have a page pagination. So we will need some props in multiple components.
Also we should persist the choice the user will make when choosing an option from the select dropdown.

2024-11-24 11:40 UTC, edichoska requested changes
Please remove comments, commented out imports. Also please remove the inline styles into classes.

2024-11-24 17:57 UTC, Tikkurilla commented
Question about the requirements:

The pagination requirements look partial.  Is there any other ticket about actually displaying the pages, total count, current page ? This looks like just defining how many items will be visible per page..or am I missing something

2024-11-24 18:06 UTC, edichoska commented
> @edichoska Question about the requirements:
> 
> The pagination requirements look partial. Is there any other ticket about actually displaying the pages, total count, current page ? This looks like just defining how many items will be visible per page..or am I missing something

Yes there was another ticket for that, already done: https://github.com/learnhubmk/app/pull/451

2024-11-24 18:36 UTC, Tikkurilla commented
@aleksandarmicev 

We need to close this PR and try to re-use the code to merge this logic under Pagination.tsx component whhic will be genetic component re-suable in all places

2024-11-28 17:46 UTC, edichoska commented
Closing this PR since we will update the Pagination.tsx component and that one will be reused everywhere

2024-11-28 17:46 UTC, closed without merging