361 Tags Add-Edit-Delete functionality
learnhubmk/app pull request #429
Opened 2024-07-24 14:07 UTC by petark7

This is a pull request for the Tags page functionality. With the current implementation, the following features are available:

1. Adding Tags (with validation)
2. Deleting Tags
3. Editing tags (with validation)

Related tickets:

[Edit tag](https://github.com/orgs/learnhubmk/projects/2/views/10?pane=issue&itemId=67577782)
[Delete tag](https://github.com/orgs/learnhubmk/projects/2/views/10?pane=issue&itemId=67592184)
[Add tag](https://github.com/orgs/learnhubmk/projects/2/views/10?pane=issue&itemId=67574996)

2024-07-31 11:22 UTC, stoimenov95 requested changes
Hey @petark7, great job on the CRUD operations regarding the tags. I successfully tested the feature, at least the first part of it. I wasn't able to search through the existing tags, and I am not sure if I should be able to apply tags to blog posts.

Can you please also check if we should have the validation messages in Macedonian?

2024-07-31 11:23 UTC, stoimenov95 commented
@petark7 please resolve the merge conflicts before submitting for the next round of review.

2024-08-04 17:58 UTC, petark7 commented on app/content-panel/tags/page.tsx
> +      .required('Tag name is required')
I think you are correct - we should have those in Macedonian and will be promptly updated.

Regarding the search feature, it wasn't requested in any of the tickets hence why I haven't implemented it but if needed I can implement it here as well.

As far as I know, currently we are not applying the tags to blog posts.

2024-08-05 17:48 UTC, edichoska commented on app/content-panel/tags/page.tsx
> +      .required('Tag name is required')
Lets create a ticket for  the search functionality. 
We will be adding tags in blog posts. That is on another ticket currently in review by jasmina

2024-08-05 17:53 UTC, edichoska commented on app/content-panel/tags/page.tsx
> +      .required('Tag name is required')
@petark7 Do we need this PR?
I saw you have created separate PRs toward the base branch: [feature/tags-base] (I already approved those)
I assume after you merge those, you are going to create a PR from `feature/tags-base` towards `staging`

2024-08-05 20:10 UTC, petark7 commented on app/content-panel/tags/page.tsx
> +      .required('Tag name is required')
@edichoska That is correct. This PR here was created due to misunderstanding and combined all the features at once which is not useful and can therefore be disregarded.

2024-08-05 20:26 UTC, closed without merging

2024-08-05 20:26 UTC, edichoska commented
Closing this PR because it is a duplicate