471 fe content panel implement forgot and reset password functionality
learnhubmk/app pull request #475
Opened 2024-12-22 15:53 UTC by mitkapanarin

- Separate API endpoints into forgotResetPswApi.ts
- Create custom hooks for form logic utils\hooks\usePasswordForm.ts
- Simplify ResetPasswordForm and ForgotPasswordForm components

2025-02-13 20:29 UTC, edichoska commented on components/reusable-components/reset-password-form/ResetPasswordForm.tsx
> +  const { formik, isLoading, error } = useResetPasswordForm(email, resetToken);
same here.

2025-02-13 20:30 UTC, edichoska commented on utils/getBaseUrl.ts
i am not sure how this got past gitleaks, but lets not hardcode urls in our code!

2025-02-13 20:40 UTC, edichoska commented
@mitkapanarin 
<img width="1463" alt="Screenshot 2025-02-13 at 21 39 34" src="https://github.com/user-attachments/assets/d8548c02-67f5-4b4e-8a31-3687b753361b" />
Can you please shorten this black rectangle so it doesn't go all the way down the page?
And also resolve the conflict

2025-02-13 20:41 UTC, edichoska commented
@mitkapanarin Please also include in the description of the PR, how this was tested and provide steps 🙏

2025-02-16 15:08 UTC, edichoska requested changes

2025-02-16 15:08 UTC, edichoska commented on utils/getBaseUrl.ts
Again please, don't hardcode urls. This plus the changes you have added to the .gitleaks.toml defeats the purpose of having gitleaks in the project.

2025-02-16 15:08 UTC, edichoska commented on utils/hooks/usePasswordForm.ts
> +  };
Do we not receive an error message from the BE?
Also you can get isError from the mutation(react-query) and you won't need to do this logic.

2025-02-16 15:08 UTC, edichoska commented on utils/hooks/usePasswordForm.ts
> +      );
Its not recommended to add detailed messages, directly into URLs, especially sensitive information.
Please handle this differently.

2025-02-16 15:08 UTC, edichoska commented on .gitleaks.toml
Help me understand the reasoning behind these changes?

2025-02-17 13:54 UTC, mitkapanarin commented on .gitleaks.toml
![alt text](image.png)

2025-02-22 14:47 UTC, edichoska reviewed
Also make sure to update the env.example with all the new process env you have in this PR

2025-03-04 12:04 UTC, mitkapanarin commented on api/utils/forgotResetPswApi.ts
> +};
Emi can you check if its ok now?

2025-03-12 18:46 UTC, dichoskaemilija commented on package.json
@mitkapanarin I assume this one is leftover from testing, but please remove -p 3000

2025-03-12 18:47 UTC, dichoskaemilija reviewed
just the tiny change and we can merge this one

2025-03-14 13:53 UTC, dichoskaemilija approved these changes
great work ⭐

2025-03-14 13:53 UTC, merged